config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts, only: [:show, :destroy]
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'restaurants#index'
  resources :restaurants do
  	resources :dishes
  end
  post 'line_items' => "line_items#create"
  delete 'carts/:id' => "carts#destroy"
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
	has_many :dishes, through: :line_items	

	def total_cart
		line_items.to_a.sum { |dish| dish.total_sum }
	end
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :restaurant
	has_one_attached :image
	validate :file_type

	def file_type
		if image.attached? && !image.content_type.in?(%w('image/jpeg' 'image/jpg'))
			errors.add(:image, 'Is not an image')
		end
	end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :dish
  belongs_to :cart

  def total_sum
  	dish.price * quantity
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :dishes, dependent: :destroy
	has_one_attached :picture
	validate :file_type

	def file_type
		if picture.attached? && !picture.content_type.in?(%w('image/jpeg' 'image/jpg'))
			errors.add(:picture, 'Is not an image')
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :cart_of_dishes

	def cart_of_dishes
		if session[:cart_id]
			cart = Cart.find_by(:id => session[:cart_id])
			if cart.present?
				@cart_of_dishes = cart
			else
				session[:cart_id] = nil
			end
		end

		if session[:cart_id] == nil
			@cart_of_dishes = Cart.create
			session[:cart_id] = @cart_of_dishes.id
		end
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart = @cart_of_dishes
	end

	def destroy
		@cart = @cart_of_dishes
		@cart.destroy
		session[:cart_id] = nil
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
	def index
    @dishes = Dish.all

	end

	def show

	end
	
	def delete

	end
	def dish_params
		params.require(:dish).permit(:title, :price, :description, :image, :quantity)
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	def create
  dish = Dish.find(params[:dish_id])
  cart_of_dishes = @cart_of_dishes

  if cart_of_dishes.dishes.include?(dish)
    @line_item = cart_of_dishes.line_items.find_by(:dish_id => dish)
    @line_item.quantity += 1
  else
    @line_item = LineItem.new
    @line_item.cart = cart_of_dishes
    @line_item.dish = dish
  end

  @line_item.save
  redirect_back(fallback_location: root_path)
end

  private

    def line_item_params
      params.require(:line_item).permit(:dish_id, :cart_id, :quantity)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		@cart = @cart_of_dishes
		@dish = Dish.find(params[:id])

		
	end
	private

	def restaurant_params
		params.require(:restaurant).permit(:name, :picture, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
    <% cart %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<span>
<% @cart.line_items.each do |item| %>
<strong class ="dish-text"><%= item.dish.title%></strong> : 
<%=item.quantity %> * <%= item.dish.price %> = 
<%= item.total_sum %>тенге <br>
<%end%>
<br>
</span>
<strong class="dish-text">Итоговая сумма:</strong><%= @cart.total_cart %>тг<br>
<%= button_to "Clear cart", cart_path, :method => :delete%>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.title %></td>
        <td><%= dish.price %></td>
        <td><%= dish.description %></td>
        <td><%= dish.restaurant.name %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab68AselKenzhebekova</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/application/navbar' %>
  
    <%= yield %>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar fixed navbar-dark bg-dark navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      &#x2630;
    </button>
    <div class="navbar-nav ml-auto">
      <div class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <div class="nav-item">
          <span class="navbar-text">
            Hello, &nbsp;
            <span>
            </div>
            <div class="dropdown show">
              <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </div>
              <div>
                <% else %>
                <div class="nav-item">
                 <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
               </div>
               <div class="nav-item">
                 <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
               </div>
               <% end %>
             </div>
           </div>
         </div>
       </div>
     </nav>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dish_id %>
    <%= form.text_field :dish_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Dish</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.dish %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dish:</strong>
  <%= @line_item.dish %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<h1>Restaurants</h1>
		
	<div class="row d-flex justify-content-around pt-3">
		<% @restaurants.each do |restaurant| %>
		<div class="card border-0">
			<%= link_to (image_tag restaurant.picture, :size => '250'),restaurant_path(restaurant) %>
			<strong class="card-text text-center"><%= restaurant.name %></strong>
		</div>
			<% end %>
	</div>
</div>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<div class="row justify-content-around py-5">
		<div class="card-hidden p-3 mb-3">
			<%= render template: "carts/show"%>
		</div> 
		<div class="card border-0">
			<strong class="card-text text-center"><%= @restaurant.name %></strong>
			<%= image_tag @restaurant.picture, size: '200' %>
			<%= @restaurant.description %>
		</div>
	</div>
	<br>
	<div class="row">
		<% @restaurant.dishes.each do |dish|%>
		<div class="col-3">
			<%= dish.title %><br>
			<%= image_tag dish.image, size: '150' %><br>
			<span><%= dish.description %></span><br>
			<span><%= dish.price %> тенге </span><br>
			<% line_item = @cart.line_items.first %>

			<% unless line_item.nil? %>
			<% if @restaurant.id == line_item.dish.restaurant.id %>
			<%= button_to "Add to cart", line_items_path(dish_id: dish) %>
			<%else%>
			<span><%="You cann`t order from this restaurant" %></span>
			<%end%>
			<%else%>
			<%= button_to "Add to cart", line_items_path(dish_id: dish)%>
		</div>
		<%end%>
		<%end%>
	</div>
	<br>
		<%= link_to 'Back', restaurants_path %>
</div>